### ISSUE TITLE
Plugin don't work on 5.6.1

### ISSUE THREAD

**Issue by TRISAF** [nabilbendafi/country-flag-fieldformatters#1]
Hi,
this plugin work's fine on 5.4 but not on 5.6.1
The error is:
__webpack_require__(...) is not a function

Any idea?

Filippo

**Comment by nabilbendafi** [comment]
This can be fixed by applying following recommendations [Kibana-plugin API 4.n => 5.n; webpack errors when compiling tutorial plugin](https://discuss.elastic.co/t/kibana-plugin-api-4-n-5-n-webpack-errors-when-compiling-tutorial-plugin/98228)
